import type { NodeConfig } from "@powerotp/contracts";

/**
 * Renders one PJSIP registration/endpoint/aor/identify block per
 * configured trunk in the pool. A rendered trunk is just "one of the
 * pool" — it is no longer tied to a verification method/type name, since
 * any trunk can serve any of the three voice methods (rotation/failover
 * happens in `apps/telephony-agent/src/trunk-pool.ts`, not here). Kept
 * intentionally simple (no failover server, no codec negotiation beyond
 * ulaw/alaw) since real trunk behavior can only be tuned once live
 * VoIP.ms credentials are attached; see `docs/PROVIDER_CHECKLIST.md` for
 * the settings to confirm before production traffic.
 */
export function renderPjsipTrunks(config: NodeConfig): string {
  const sections = config.trunks.map((trunk) => renderTrunk(trunk));

  const header =
    "; Generated by apps/telephony-agent from the control plane's /v1/nodes/config.\n" +
    "; Do not edit by hand: changes are overwritten on the next poll.\n\n";

  return sections.length > 0
    ? header + sections.join("\n")
    : header + "; No outbound trunks are currently configured for this node.\n";
}

function renderTrunk(trunk: { id: string; url: string; user: string; pass: string }): string {
  const id = trunk.id;
  const host = new URL(trunk.url.includes("://") ? trunk.url : `sip://${trunk.url}`).hostname;

  return [
    `[${id}]`,
    "type=registration",
    `outbound_auth=${id}-auth`,
    `server_uri=sip:${host}`,
    `client_uri=sip:${trunk.user}@${host}`,
    "retry_interval=60",
    "",
    `[${id}-auth]`,
    "type=auth",
    "auth_type=userpass",
    `username=${trunk.user}`,
    `password=${trunk.pass}`,
    "",
    `[${id}]`,
    "type=aor",
    `contact=sip:${trunk.user}@${host}`,
    "",
    `[${id}]`,
    "type=endpoint",
    "context=powerotp-outbound",
    "disallow=all",
    "allow=ulaw,alaw",
    `outbound_auth=${id}-auth`,
    `aors=${id}`,
    `from_user=${trunk.user}`,
    "",
    `[${id}]`,
    "type=identify",
    `endpoint=${id}`,
    `match=${host}`,
    "",
  ].join("\n");
}
